image: Ubuntu1804
stack: node 18

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

build: off

# Этот код использует сценарий npm, который выполняет обе команды тестирования.
test_script: npm test:unit


