image: Ubuntu1804
stack: node 18

branches:
  only:
    - master

cache:
  directories:
    - node_modules

install:
  - npm install

build: off

# Этот код использует свойство `steps` для определения двух команд тестирования.
steps:
- npm run lint
- npm run test


